### PR TITLE
Create compile.sh for example 03 and compile mkts_old used in compile.

### PR DESCRIPTION
**Pull request by jespicas**
Create compile.sh and compile mkts_old in linux

### CODE REVIEW

**Comment by mojontwins** [comment]
Please double-check because the newly generated game assets contain incorrect data. 

- For example notice how the data in examples/03_cheril_of_the_bosque_v1/dev/assets/cutsb.h is getting cleared (palette data all zeroes, tile data all 169s)
- Palettes in examples/03_cheril_of_the_bosque_v1/dev/assets/palettes.h are all 0x0F (pure black).
- etc...

Usually this behaviour is related to mkts misbehaving or not being able to read input files (thus processing "all pixels are black" images).

**Comment by jespicas** [comment]
Hi,
In this pull-request I add a mkts_old file , was found in other repository, Can you confirm this code is last version? I'll check if mkts_old generate files as spectec, I think could be the problem.

**Comment by mojontwins** [comment]
I just checked /src/utils/legacy/mkts_old.bas and it's correct. I recompiled it for win32 just to make sure, then built example 03 with no issues. Maybe a path problem in the build script? Thanks for your efforts.

**Comment by jespicas** [comment]
I think following the problem, a libfbpng installed in my machine not is a good ones. I searching version for Ubuntu 18.04 and I don't found. I'll try to download source version and recompile in my machine and see what happens.

**Comment by jespicas** [comment]
Ready to check

**Pull request closed without merging**
